# -*- coding: utf-8 -*-
"""number_classification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jHPQAl37XTKdHUD_xo4nqIZOly-sCyc5
"""

from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Activation,Dense,Dropout
from tensorflow.keras.models import Sequential
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.utils import to_categorical
import numpy as np 
import matplotlib.pyplot as plt


(train_images,train_labels),(test_images,test_labels) = mnist.load_data()

print(train_images.shape)

train_images = train_images.reshape((train_images.shape[0],784))
test_images = test_images.reshape((test_images.shape[0],784))

train_labels = to_categorical(train_labels)
test_labels = to_categorical(test_labels)

model = Sequential()
model.add(Dense(256,activation='sigmoid',input_shape=(784,)))
model.add(Dense(128,activation='sigmoid'))
model.add(Dropout(rate=0.5))
model.add(Dense(10,activation='softmax'))

model.compile(loss='categorical_crossentropy',optimizer=SGD(lr=0.1),metrics=['acc'])

history = model.fit(train_images,train_labels,batch_size=500,epochs=5,validation_split=0.2)

plt.plot(history.history['acc'],label='acc')
plt.plot(history.history['val_acc'],label='val_acc')
plt.ylabel('accuracy')
plt.xlabel('epoch')

plt.legend(loc='best')
plt.show()

test_loss,test_acc = model.evaluate(test_images,test_labels)
print('loss: {:.3f}\nacc:{:.3f}'.format(test_loss,test_acc))

for i in range(10):
  plt.subplot(1,10,i+1)
  plt.imshow(test_images[i].reshape(28,28),'gray')
plt.show()

test_predictions = model.predict(test_images[0:10])
test_predictions = np.argmax(test_predictions,axis=1)
print(test_predictions)